import { CableRun, NetworkNode, Structure } from '../types/network';

export interface PresetTopology {
  id: string;
  name: string;
  badge: string;
  description: string;
  structures: Structure[];
  nodes: NetworkNode[];
  cables: CableRun[];
}

export const PRESET_TOPOLOGIES: PresetTopology[] = [
  {
    id: 'standard-campus',
    name: 'Main Facility & Covered Assembly Area (Dual-Zone)',
    badge: 'Dual-Zone Campus',
    description:
      'Standard multi-facility architecture: Fiber optic hand-off into Main Administration Building with an Indoor AP and an outdoor weatherproof AP covering the covered assembly / recreational grounds.',
    structures: [
      {
        id: 'bldg-hall',
        label: 'Main Facility (Administration)',
        type: 'barangay_hall',
        x: 40,
        y: 40,
        width: 380,
        height: 480,
        color: '#1e293b',
      },
      {
        id: 'bldg-court',
        label: 'Covered Assembly Grounds',
        type: 'covered_court',
        x: 480,
        y: 40,
        width: 420,
        height: 480,
        color: '#0f172a',
      },
    ],
    nodes: [
      // Power
      {
        id: 'ac-1',
        type: 'ac_power',
        label: '220V AC Wall Outlet',
        structureId: 'bldg-hall',
        position: { x: 70, y: 80 },
        power: { requiresPower: false, source: 'none', wattage: 0 },
        status: 'green',
        faults: [],
      },
      {
        id: 'ups-1',
        type: 'ups',
        label: 'Online UPS (1-Socket)',
        structureId: 'bldg-hall',
        position: { x: 70, y: 180 },
        power: { requiresPower: true, source: 'ac', wattage: 15, upsCapacityVA: 1000 },
        status: 'green',
        faults: [],
      },
      // Backbone
      {
        id: 'nap-1',
        type: 'isp_nap',
        label: 'Fiber Backbone Demarcation',
        structureId: 'bldg-hall',
        position: { x: 70, y: 290 },
        power: { requiresPower: false, source: 'none', wattage: 0 },
        status: 'green',
        faults: [],
      },
      {
        id: 'ont-1',
        type: 'ont_onu',
        label: 'Fiber ONT / ONU (ISP Provided)',
        structureId: 'bldg-hall',
        position: { x: 70, y: 400 },
        power: { requiresPower: true, source: 'ac', wattage: 12 },
        status: 'green',
        faults: [],
      },
      // Core
      {
        id: 'router-1',
        type: 'router_firewall',
        label: 'Core Gateway Router',
        structureId: 'bldg-hall',
        position: { x: 230, y: 160 },
        power: { requiresPower: true, source: 'ac', wattage: 24 },
        network: {
          ip: '192.168.1.1',
          subnet: '255.255.255.0',
          gateway: '192.168.1.1',
          isDhcp: false,
          dns: '8.8.8.8',
        },
        status: 'green',
        faults: [],
      },
      {
        id: 'switch-1',
        type: 'core_switch_poe',
        label: '8-Port Managed PoE+ Switch',
        structureId: 'bldg-hall',
        position: { x: 230, y: 310 },
        power: { requiresPower: true, source: 'ac', wattage: 30, poeBudgetWatts: 130 },
        network: {
          ip: '192.168.1.2',
          subnet: '255.255.255.0',
          gateway: '192.168.1.1',
          isDhcp: false,
        },
        status: 'green',
        faults: [],
      },
      // Indoor AP
      {
        id: 'ap-indoor-1',
        type: 'indoor_ap',
        label: 'Main Lobby Ceiling AP',
        structureId: 'bldg-hall',
        position: { x: 230, y: 430 },
        power: { requiresPower: true, source: 'poe', requiredStandard: '802.3af', wattage: 11 },
        network: {
          ip: '192.168.1.10',
          subnet: '255.255.255.0',
          gateway: '192.168.1.1',
          isDhcp: false,
          ssid: 'TEPBIZ-SECURE-WIFI',
        },
        status: 'green',
        faults: [],
      },
      // Surge protector & outdoor AP in covered court
      {
        id: 'arrester-1',
        type: 'surge_arrester',
        label: 'Outdoor Surge Arrester',
        structureId: 'bldg-court',
        position: { x: 520, y: 140 },
        power: { requiresPower: false, source: 'none', wattage: 0 },
        status: 'green',
        faults: [],
      },
      {
        id: 'ap-outdoor-1',
        type: 'outdoor_ap',
        label: 'Assembly Grounds AP',
        structureId: 'bldg-court',
        position: { x: 670, y: 140 },
        power: { requiresPower: true, source: 'poe', requiredStandard: '802.3at', wattage: 22 },
        network: {
          ip: '192.168.1.20',
          subnet: '255.255.255.0',
          gateway: '192.168.1.1',
          isDhcp: false,
          ssid: 'TEPBIZ-OUTDOOR-WIFI',
        },
        status: 'green',
        faults: [],
      },
      // Client Devices
      {
        id: 'client-1',
        type: 'client_device',
        label: 'Laptop Workstation (Lobby)',
        structureId: 'bldg-hall',
        position: { x: 340, y: 430 },
        power: { requiresPower: false, source: 'none', wattage: 0 },
        network: {
          ip: '192.168.1.101',
          subnet: '255.255.255.0',
          gateway: '192.168.1.1',
          isDhcp: true,
        },
        status: 'green',
        faults: [],
      },
      {
        id: 'client-2',
        type: 'client_device',
        label: 'Mobile Device (Court)',
        structureId: 'bldg-court',
        position: { x: 780, y: 260 },
        power: { requiresPower: false, source: 'none', wattage: 0 },
        network: {
          ip: '192.168.1.102',
          subnet: '255.255.255.0',
          gateway: '192.168.1.1',
          isDhcp: true,
        },
        status: 'green',
        faults: [],
      },
    ],
    cables: [
      // Power wiring
      {
        id: 'c-ac-1',
        type: 'ac_power',
        fromNodeId: 'ac-1',
        fromPortId: 'ac_out',
        toNodeId: 'ups-1',
        toPortId: 'ac_in',
        lengthMeters: 2,
        status: 'green',
        faults: [],
      },
      {
        id: 'c-ac-2',
        type: 'ac_power',
        fromNodeId: 'ups-1',
        fromPortId: 'ac_out',
        toNodeId: 'switch-1',
        toPortId: 'pwr_in',
        lengthMeters: 2,
        status: 'green',
        faults: [],
      },
      {
        id: 'c-ac-3',
        type: 'ac_power',
        fromNodeId: 'ac-1',
        fromPortId: 'ac_out',
        toNodeId: 'router-1',
        toPortId: 'pwr_in',
        lengthMeters: 2,
        status: 'green',
        faults: [],
      },
      {
        id: 'c-ac-4',
        type: 'ac_power',
        fromNodeId: 'ac-1',
        fromPortId: 'ac_out',
        toNodeId: 'ont-1',
        toPortId: 'pwr_in',
        lengthMeters: 2,
        status: 'green',
        faults: [],
      },
      // Backbone fiber
      {
        id: 'c-fiber-1',
        type: 'fiber',
        fromNodeId: 'nap-1',
        fromPortId: 'fiber_out',
        toNodeId: 'ont-1',
        toPortId: 'pon_in',
        lengthMeters: 15,
        status: 'green',
        faults: [],
      },
      // ONT to Router WAN
      {
        id: 'c-eth-1',
        type: 'ethernet',
        fromNodeId: 'ont-1',
        fromPortId: 'lan_out',
        toNodeId: 'router-1',
        toPortId: 'wan_port',
        lengthMeters: 3,
        status: 'green',
        faults: [],
      },
      // Router LAN to Switch Uplink
      {
        id: 'c-eth-2',
        type: 'ethernet',
        fromNodeId: 'router-1',
        fromPortId: 'lan_port1',
        toNodeId: 'switch-1',
        toPortId: 'uplink',
        lengthMeters: 2,
        status: 'green',
        faults: [],
      },
      // Switch PoE to Indoor AP
      {
        id: 'c-eth-3',
        type: 'ethernet',
        fromNodeId: 'switch-1',
        fromPortId: 'poe1',
        toNodeId: 'ap-indoor-1',
        toPortId: 'poe_in',
        lengthMeters: 18,
        status: 'green',
        faults: [],
      },
      // Switch PoE to Surge Arrester
      {
        id: 'c-eth-4',
        type: 'ethernet',
        fromNodeId: 'switch-1',
        fromPortId: 'poe2',
        toNodeId: 'arrester-1',
        toPortId: 'eth_in',
        lengthMeters: 45,
        status: 'green',
        faults: [],
      },
      // Surge Arrester to Outdoor AP
      {
        id: 'c-eth-5',
        type: 'ethernet',
        fromNodeId: 'arrester-1',
        fromPortId: 'eth_out',
        toNodeId: 'ap-outdoor-1',
        toPortId: 'poe_in',
        lengthMeters: 5,
        status: 'green',
        faults: [],
      },
      // Grounding wire on outdoor AP
      {
        id: 'c-gnd-1',
        type: 'grounding',
        fromNodeId: 'arrester-1',
        fromPortId: 'gnd',
        toNodeId: 'ap-outdoor-1',
        toPortId: 'gnd',
        lengthMeters: 3,
        status: 'green',
        faults: [],
      },
      // Wi-Fi links to clients
      {
        id: 'c-wifi-1',
        type: 'ethernet',
        fromNodeId: 'ap-indoor-1',
        fromPortId: 'poe_in',
        toNodeId: 'client-1',
        toPortId: 'wifi_link',
        lengthMeters: 5,
        status: 'green',
        faults: [],
      },
      {
        id: 'c-wifi-2',
        type: 'ethernet',
        fromNodeId: 'ap-outdoor-1',
        fromPortId: 'poe_in',
        toNodeId: 'client-2',
        toPortId: 'wifi_link',
        lengthMeters: 15,
        status: 'green',
        faults: [],
      },
    ],
  },

  {
    id: 'satellite-remote-facility',
    name: 'Remote Facility - Satellite Backbone (VSAT)',
    badge: 'Satellite Backhaul',
    description:
      'Isolated facility with no terrestrial fiber access. Powered by 220V grid/solar with a VSAT Satellite Dish terminal providing broadband link to client workstations and access points.',
    structures: [
      {
        id: 'bldg-clinic',
        label: 'Main Operations Facility',
        type: 'health_center',
        x: 40,
        y: 40,
        width: 420,
        height: 480,
        color: '#042f2e',
      },
      {
        id: 'bldg-waiting',
        label: 'Annex / Outdoor Waiting Station',
        type: 'generic',
        x: 520,
        y: 80,
        width: 320,
        height: 380,
        color: '#1e293b',
      },
    ],
    nodes: [
      {
        id: 'ac-rhu',
        type: 'ac_power',
        label: 'Mains / Inverter (220V)',
        structureId: 'bldg-clinic',
        position: { x: 70, y: 90 },
        power: { requiresPower: false, source: 'none', wattage: 0 },
        status: 'green',
        faults: [],
      },
      {
        id: 'vsat-1',
        type: 'vsat_terminal',
        label: 'VSAT Satellite Transceiver',
        structureId: 'bldg-clinic',
        position: { x: 70, y: 220 },
        power: { requiresPower: true, source: 'ac', wattage: 65 },
        status: 'green',
        faults: [],
      },
      {
        id: 'router-rhu',
        type: 'router_firewall',
        label: 'Edge Gateway Router',
        structureId: 'bldg-clinic',
        position: { x: 230, y: 150 },
        power: { requiresPower: true, source: 'ac', wattage: 24 },
        network: {
          ip: '192.168.10.1',
          subnet: '255.255.255.0',
          gateway: '192.168.10.1',
          isDhcp: false,
        },
        status: 'green',
        faults: [],
      },
      {
        id: 'poe-inj-1',
        type: 'poe_injector',
        label: '30W PoE+ Injector',
        structureId: 'bldg-clinic',
        position: { x: 230, y: 280 },
        power: { requiresPower: true, source: 'ac', wattage: 3, poeBudgetWatts: 30 },
        status: 'green',
        faults: [],
      },
      {
        id: 'ap-waiting',
        type: 'outdoor_ap',
        label: 'Outdoor Annex AP',
        structureId: 'bldg-waiting',
        position: { x: 600, y: 180 },
        power: { requiresPower: true, source: 'poe', requiredStandard: '802.3at', wattage: 22 },
        network: {
          ip: '192.168.10.15',
          subnet: '255.255.255.0',
          gateway: '192.168.10.1',
          isDhcp: false,
          ssid: 'TEPBIZ-REMOTE-WIFI',
        },
        status: 'green',
        faults: [],
      },
      {
        id: 'arrester-rhu',
        type: 'surge_arrester',
        label: 'Surge Arrester & Ground',
        structureId: 'bldg-waiting',
        position: { x: 600, y: 310 },
        power: { requiresPower: false, source: 'none', wattage: 0 },
        status: 'green',
        faults: [],
      },
    ],
    cables: [
      {
        id: 'c-gida-ac1',
        type: 'ac_power',
        fromNodeId: 'ac-rhu',
        fromPortId: 'ac_out',
        toNodeId: 'vsat-1',
        toPortId: 'pwr_in',
        lengthMeters: 5,
        status: 'green',
        faults: [],
      },
      {
        id: 'c-gida-ac2',
        type: 'ac_power',
        fromNodeId: 'ac-rhu',
        fromPortId: 'ac_out',
        toNodeId: 'router-rhu',
        toPortId: 'pwr_in',
        lengthMeters: 3,
        status: 'green',
        faults: [],
      },
      {
        id: 'c-gida-ac3',
        type: 'ac_power',
        fromNodeId: 'ac-rhu',
        fromPortId: 'ac_out',
        toNodeId: 'poe-inj-1',
        toPortId: 'pwr_in',
        lengthMeters: 2,
        status: 'green',
        faults: [],
      },
      {
        id: 'c-gida-sat',
        type: 'ethernet',
        fromNodeId: 'vsat-1',
        fromPortId: 'sat_lan',
        toNodeId: 'router-rhu',
        toPortId: 'wan_port',
        lengthMeters: 8,
        status: 'green',
        faults: [],
      },
      {
        id: 'c-gida-lan',
        type: 'ethernet',
        fromNodeId: 'router-rhu',
        fromPortId: 'lan_port1',
        toNodeId: 'poe-inj-1',
        toPortId: 'data_in',
        lengthMeters: 2,
        status: 'green',
        faults: [],
      },
      {
        id: 'c-gida-poe',
        type: 'ethernet',
        fromNodeId: 'poe-inj-1',
        fromPortId: 'poe_out',
        toNodeId: 'ap-waiting',
        toPortId: 'poe_in',
        lengthMeters: 40,
        status: 'green',
        faults: [],
      },
      {
        id: 'c-gida-gnd',
        type: 'grounding',
        fromNodeId: 'ap-waiting',
        fromPortId: 'gnd',
        toNodeId: 'arrester-rhu',
        toPortId: 'gnd',
        lengthMeters: 3,
        status: 'green',
        faults: [],
      },
    ],
  },
  {
    id: 'blank-site',
    name: 'Blank Custom Canvas',
    badge: 'Custom',
    description: 'Empty workspace with an initial facility structure block ready for your custom site planning.',
    structures: [
      {
        id: 'bldg-initial',
        label: 'Facility Block 1',
        type: 'barangay_hall',
        x: 60,
        y: 60,
        width: 440,
        height: 480,
        color: '#1e293b',
      },
    ],
    nodes: [
      {
        id: 'ac-base',
        type: 'ac_power',
        label: '220V AC Mains',
        structureId: 'bldg-initial',
        position: { x: 100, y: 120 },
        power: { requiresPower: false, source: 'none', wattage: 0 },
        status: 'green',
        faults: [],
      },
      {
        id: 'nap-base',
        type: 'isp_nap',
        label: 'ISP Fiber Demarcation',
        structureId: 'bldg-initial',
        position: { x: 100, y: 260 },
        power: { requiresPower: false, source: 'none', wattage: 0 },
        status: 'green',
        faults: [],
      },
    ],
    cables: [],
  },
];
